# Generated by Django 4.2.4 on 2023-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
