# Generated by Django 4.2.4 on 2023-08-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_options_member_create_date_and_more'),
        ('product', '0003_product_create_date_product_update_date_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_number',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
