# Generated by Django 4.2.4 on 2023-08-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_password',
        ),
    ]
