# Generated by Django 4.2.4 on 2023-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
