# Generated by Django 4.2.4 on 2023-08-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
